// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhzvYTeSylVYEkpR9XrANH3yOwnobto3E',
    appId: '1:1048838563120:web:1804044d7dda825af254f5',
    messagingSenderId: '1048838563120',
    projectId: 'esp-to-firebase-test',
    authDomain: 'esp-to-firebase-test.firebaseapp.com',
    databaseURL: 'https://esp-to-firebase-test-default-rtdb.firebaseio.com',
    storageBucket: 'esp-to-firebase-test.appspot.com',
    measurementId: 'G-LFNMF70MDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_CFxTf4NGnY4PmL1plcfj1sP6OL49XAg',
    appId: '1:1048838563120:android:73f8c07564e7f24af254f5',
    messagingSenderId: '1048838563120',
    projectId: 'esp-to-firebase-test',
    databaseURL: 'https://esp-to-firebase-test-default-rtdb.firebaseio.com',
    storageBucket: 'esp-to-firebase-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX2lQ3snX5X9Zg9yDlH9278c3wMAiNdPQ',
    appId: '1:1048838563120:ios:0434aa25e4ffb3ecf254f5',
    messagingSenderId: '1048838563120',
    projectId: 'esp-to-firebase-test',
    databaseURL: 'https://esp-to-firebase-test-default-rtdb.firebaseio.com',
    storageBucket: 'esp-to-firebase-test.appspot.com',
    iosClientId: '1048838563120-k0a3c6f5qupr6t5uks4gervqu185hjhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX2lQ3snX5X9Zg9yDlH9278c3wMAiNdPQ',
    appId: '1:1048838563120:ios:0434aa25e4ffb3ecf254f5',
    messagingSenderId: '1048838563120',
    projectId: 'esp-to-firebase-test',
    databaseURL: 'https://esp-to-firebase-test-default-rtdb.firebaseio.com',
    storageBucket: 'esp-to-firebase-test.appspot.com',
    iosClientId: '1048838563120-k0a3c6f5qupr6t5uks4gervqu185hjhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhzvYTeSylVYEkpR9XrANH3yOwnobto3E',
    appId: '1:1048838563120:web:3eb31b744605ac7ff254f5',
    messagingSenderId: '1048838563120',
    projectId: 'esp-to-firebase-test',
    authDomain: 'esp-to-firebase-test.firebaseapp.com',
    databaseURL: 'https://esp-to-firebase-test-default-rtdb.firebaseio.com',
    storageBucket: 'esp-to-firebase-test.appspot.com',
    measurementId: 'G-EZ4CMF3BM7',
  );
}
